CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL     VARCHAR,
    LOGIN     VARCHAR,
    USER_NAME VARCHAR,
    BIRTHDAY  DATE
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   INT PRIMARY KEY,
    GENRE_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS RATINGS
(
    RATINGMPAA_ID INT PRIMARY KEY,
    RATING_NAME   VARCHAR
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    LIKESCOUNT    INT,
    FILM_NAME     VARCHAR,
    DESCRIPTION   VARCHAR,
    RELEASE_DATE  DATE,
    DURATION      INT,
    RATINGMPAA_ID INT REFERENCES RATINGS (RATINGMPAA_ID)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    FILM_GENRE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FILM_ID       BIGINT REFERENCES FILMS (FILM_ID),
    GENRE_ID      INT REFERENCES GENRES (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    FRIENDSTATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         INT REFERENCES USERS (USER_ID),
    FRIEND_ID       INT REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDSTATUS
(
    FRIENDSTATUS_ID INT REFERENCES FRIENDS (FRIENDSTATUS_ID),
    STATUSNAME      VARCHAR
);

CREATE TABLE IF NOT EXISTS LIKES
(
    LIKE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT REFERENCES USERS (USER_ID),
    FILM_ID BIGINT REFERENCES FILMS (FILM_ID)

);



MERGE INTO RATINGS
    VALUES (1, 'G'),
           (2, 'PG'),
           (3, 'PG-13'),
           (4, 'R'),
           (5, 'NC-17');

MERGE INTO GENRES
    VALUES (1, 'Комедия'),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');